### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by paolobarbolini** [cptrodgers/simple-aws-s3#1]
Hello, I saw your new crate in the _new crates_ section on crates.io. I also [have a crate](https://crates.io/crates/rusty-s3) for working with S3. Maybe we should merge efforts?

**Comment by cptrodgers** [comment]
Hi @paolobarbolini , sure, It will be better than standalone. I found your lib but it not cover my demand (Presigned Post and Presigned Get). Do you have discord server or chatting room for `rusty-s3`.

**Comment by paolobarbolini** [comment]
We don't have a chatroom for rusty-s3, but if you'd like to contact me I do have Matrix [@paolobarbolini:matrix.org](https://matrix.to/#/@paolobarbolini:matrix.org) and Discord `Paolo Barbolini#4465`

**Comment by paolobarbolini** [comment]
Anyway we do support presigned urls. Not presigned POST ATM, but it would be very easy to add https://github.com/paolobarbolini/rusty-s3/blob/main/examples/sign_get.rs

**Comment by cptrodgers** [comment]
Ah, I see. Sent request on discord.
